//! `norn init conventions` — scans the project and writes a starter
//! `CONVENTIONS.toml` (NTC-004).
//!
//! The handler walks the working directory to learn which bundled language
//! templates apply, augments those language definitions with supported tools
//! discovered on `PATH`, then emits convention rules that activate the tools
//! declared by those definitions. Every generated activation uses
//! `handling = "advise"` so adoption is non-blocking, but the emitted
//! advisories are still required fix feedback rather than optional notes.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use diagnostics::conventions::{ConventionsConfig, LangDef};
use diagnostics::language_packs::{file_extension_to_language, template_for_language};

use crate::cli::ExitCode;

/// Default output filename, resolved against the current working directory.
const DEFAULT_FILENAME: &str = "CONVENTIONS.toml";

/// Printed when the default file already exists; the exact wording is part
/// of the NTC-004 R7 contract.
const ALREADY_EXISTS_MESSAGE: &str =
    "CONVENTIONS.toml already exists, use --output to write to a different path";

/// Header comment block prepended to every generated file.
const HEADER: &str = "\
# CONVENTIONS.toml — post-mutation check configuration for Norn.
#
# Language definitions declare available tools. Rules activate those tools after
# write / edit / apply_patch mutations. `handling = \"advise\"` is non-blocking
# transport, not optional guidance: the agent must fix every advisory properly
# before claiming completion. `handling = \"block\"` emits a validation failure;
# gate-mode tools reject the call, while report-mode tools return committed
# output with a structured validation error because the mutation already landed.
# Generated by `norn init conventions`; review deliberately before broad use.

";

/// Mutation tools that activate every generated rule.
fn default_tools() -> Vec<String> {
    vec![
        "write".to_owned(),
        "edit".to_owned(),
        "apply_patch".to_owned(),
    ]
}

/// Complete generated conventions prior to TOML rendering.
#[derive(Debug, Clone, PartialEq, Eq)]
struct GeneratedConventions {
    language_definitions: String,
    rules: Vec<GeneratedRule>,
}

/// An in-memory convention rule prior to TOML rendering. Kept separate from
/// the `diagnostics` / runtime types so generation rules stay explicit and
/// independently testable.
#[derive(Debug, Clone, PartialEq, Eq)]
struct GeneratedRule {
    name: String,
    tools: Vec<String>,
    paths: Vec<String>,
    /// `(limit, handling)` for the file-length check, or `None` when the
    /// rule has no LOC limit.
    loc: Option<(u64, &'static str)>,
    lsp_diagnostics: bool,
    activations: Vec<String>,
    priority: i32,
}

/// Run `norn init conventions`.
pub fn run_conventions(output: Option<PathBuf>) -> ExitCode {
    let cwd = match std::env::current_dir() {
        Ok(dir) => dir,
        Err(err) => {
            eprintln!("norn: cannot resolve working directory: {err}");
            return ExitCode::AgentError;
        }
    };

    let extensions = match scan_project_extensions(&cwd) {
        Ok(map) => map,
        Err(err) => {
            eprintln!("norn: failed to scan project for file types: {err}");
            return ExitCode::AgentError;
        }
    };

    let generated = match generate_conventions(&extensions, &tool_on_path) {
        Ok(generated) => generated,
        Err(err) => {
            eprintln!("norn: failed to generate conventions: {err}");
            return ExitCode::AgentError;
        }
    };
    let rendered = render_conventions(&generated);

    let _descriptor_permit = match norn::resource::acquire_filesystem_operation() {
        Ok(permit) => permit,
        Err(err) => {
            eprintln!("norn: cannot admit conventions output operation: {err}");
            return ExitCode::AgentError;
        }
    };

    let target = if let Some(path) = output {
        if path.is_absolute() {
            path
        } else {
            cwd.join(path)
        }
    } else {
        let default_path = cwd.join(DEFAULT_FILENAME);
        if default_path.exists() {
            println!("{ALREADY_EXISTS_MESSAGE}");
            return ExitCode::Success;
        }
        default_path
    };

    if let Err(err) = std::fs::write(&target, rendered) {
        eprintln!("norn: failed to write {}: {err}", target.display());
        return ExitCode::AgentError;
    }

    println!(
        "Wrote {} ({} language definition{}, {} rule{}).",
        target.display(),
        generated_language_count(&generated.language_definitions),
        if generated_language_count(&generated.language_definitions) == 1 {
            ""
        } else {
            "s"
        },
        generated.rules.len(),
        if generated.rules.len() == 1 { "" } else { "s" }
    );
    ExitCode::Success
}

/// Walk `root` recursively, counting file extensions. Hidden directories
/// (names starting with `.`, which covers `.git`), `target`, and
/// `node_modules` are skipped. Extensions are lowercased for stability.
fn scan_project_extensions(root: &Path) -> std::io::Result<BTreeMap<String, usize>> {
    let _descriptor_permit =
        norn::resource::acquire_filesystem_operation().map_err(std::io::Error::other)?;
    let mut counts: BTreeMap<String, usize> = BTreeMap::new();
    let mut stack = vec![root.to_path_buf()];

    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir)? {
            let entry = entry?;
            let file_type = entry.file_type()?;
            let name = entry.file_name();
            let name = name.to_string_lossy();

            if file_type.is_dir() {
                if name.starts_with('.') || name == "target" || name == "node_modules" {
                    continue;
                }
                stack.push(entry.path());
            } else if file_type.is_file() {
                let path = entry.path();
                if let Some(ext) = path.extension() {
                    let ext = ext.to_string_lossy().to_lowercase();
                    *counts.entry(ext).or_insert(0) += 1;
                }
            }
        }
    }

    Ok(counts)
}

/// Probe `PATH` for an external tool by attempting `tool --version`. A
/// successful spawn (any exit status) means the binary exists; a spawn
/// error (typically not-found) means it is absent. Missing tools are
/// silent — no warning, no error.
fn tool_on_path(tool: &str) -> bool {
    let _descriptor_permit = match norn::resource::acquire_output_subprocess() {
        Ok(permit) => permit,
        Err(error) => {
            tracing::warn!(%error, tool, "conventions tool probe admission refused");
            return false;
        }
    };
    std::process::Command::new(tool)
        .arg("--version")
        .output()
        .is_ok()
}

/// Generate language definitions and rules from the detected extension
/// counts. `probe` reports whether an external tool is available on `PATH`;
/// it is injected so tests can exercise tool inclusion deterministically.
fn generate_conventions(
    extensions: &BTreeMap<String, usize>,
    probe: &dyn Fn(&str) -> bool,
) -> Result<GeneratedConventions, String> {
    let languages = detected_languages(extensions);
    let language_definitions = generate_language_definitions(&languages, probe)?;
    let parsed = ConventionsConfig::load_from_str(&language_definitions)
        .map_err(|err| format!("generated language definitions do not load: {err}"))?;
    let rules = generate_rules(extensions, parsed.lang_defs());

    Ok(GeneratedConventions {
        language_definitions,
        rules,
    })
}

fn detected_languages(extensions: &BTreeMap<String, usize>) -> BTreeSet<String> {
    extensions
        .keys()
        .filter_map(|extension| file_extension_to_language(extension).map(str::to_owned))
        .collect()
}

fn generate_language_definitions(
    languages: &BTreeSet<String>,
    probe: &dyn Fn(&str) -> bool,
) -> Result<String, String> {
    let mut out = String::new();

    for language in languages {
        let template = template_for_language(language).ok_or_else(|| {
            format!("missing bundled template for detected language `{language}`")
        })?;
        let config = ConventionsConfig::load_from_str(template)
            .map_err(|err| format!("bundled template for `{language}` does not load: {err}"))?;
        let mut extra_diagnostics = Vec::new();
        for tool in path_augmented_diagnostics(language) {
            if probe(tool) && config.lookup_tool(language, tool).is_none() {
                extra_diagnostics.push((*tool).to_owned());
            }
        }

        let augmented = augment_template_with_diagnostics(template, language, &extra_diagnostics);
        out.push_str(&augmented);
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }

    Ok(out)
}

fn path_augmented_diagnostics(language: &str) -> &'static [&'static str] {
    match language {
        "python" => &["mypy", "ruff"],
        "typescript" => &["eslint", "biome"],
        _ => &[],
    }
}

fn augment_template_with_diagnostics(template: &str, language: &str, tools: &[String]) -> String {
    if tools.is_empty() {
        return template.to_owned();
    }

    let diagnostics_header = format!("[{language}.diagnostics]");
    let diagnostic_lines = tools
        .iter()
        .map(|tool| format!("{tool} = {{ target = \"file\", handling = \"advise\", args = [] }}"))
        .collect::<Vec<_>>();

    if !template
        .lines()
        .any(|line| line.trim() == diagnostics_header)
    {
        let mut out = template.to_owned();
        if !out.ends_with('\n') {
            out.push('\n');
        }
        let _ = writeln!(out, "\n{diagnostics_header}");
        for line in diagnostic_lines {
            let _ = writeln!(out, "{line}");
        }
        return out;
    }

    let mut out = String::new();
    for line in template.lines() {
        let _ = writeln!(out, "{line}");
        if line.trim() == diagnostics_header {
            for diagnostic_line in &diagnostic_lines {
                let _ = writeln!(out, "{diagnostic_line}");
            }
        }
    }
    out
}

fn generate_rules(
    extensions: &BTreeMap<String, usize>,
    lang_defs: &BTreeMap<String, LangDef>,
) -> Vec<GeneratedRule> {
    let mut rules = Vec::new();

    for (language, lang_def) in lang_defs {
        let paths = language_paths(language, extensions);
        if paths.is_empty() {
            continue;
        }

        rules.push(GeneratedRule {
            name: format!("{language}-general"),
            tools: default_tools(),
            paths,
            loc: general_loc(language),
            lsp_diagnostics: lang_def.lsp.is_some(),
            activations: flat_activations(lang_def),
            priority: 0,
        });

        if language == "rust" {
            rules.push(GeneratedRule {
                name: "rust-entrypoints".to_owned(),
                tools: default_tools(),
                paths: vec![
                    "**/mod.rs".to_owned(),
                    "**/lib.rs".to_owned(),
                    "**/main.rs".to_owned(),
                ],
                loc: Some((200, "advise")),
                lsp_diagnostics: lang_def.lsp.is_some(),
                activations: flat_activations(lang_def),
                priority: 10,
            });
        }
    }

    rules
}

fn language_paths(language: &str, extensions: &BTreeMap<String, usize>) -> Vec<String> {
    match language {
        "rust" => paths_for_extensions(extensions, &["rs"]),
        "typescript" => paths_for_extensions(extensions, &["ts", "tsx", "js", "jsx"]),
        "python" => paths_for_extensions(extensions, &["py", "pyi"]),
        "go" => paths_for_extensions(extensions, &["go"]),
        "gleam" => paths_for_extensions(extensions, &["gleam"]),
        _ => Vec::new(),
    }
}

fn paths_for_extensions(extensions: &BTreeMap<String, usize>, candidates: &[&str]) -> Vec<String> {
    let mut paths = Vec::new();
    for extension in candidates {
        if extensions.contains_key(*extension) {
            paths.push(format!("*.{extension}"));
            paths.push(format!("**/*.{extension}"));
        }
    }
    paths
}

fn general_loc(language: &str) -> Option<(u64, &'static str)> {
    match language {
        "rust" => Some((500, "advise")),
        "typescript" | "go" => Some((400, "advise")),
        "python" => Some((300, "advise")),
        _ => None,
    }
}

fn flat_activations(lang_def: &LangDef) -> Vec<String> {
    let lsp_check = lang_def.lsp.as_ref().and_then(|lsp| lsp.check.as_deref());
    let mut activations = BTreeSet::new();

    if let Some(diagnostics) = lang_def.diagnostics.as_ref() {
        for tool in diagnostics.keys() {
            if Some(tool.as_str()) != lsp_check {
                activations.insert(tool.clone());
            }
        }
    }

    if let Some(patterns) = lang_def.patterns.as_ref() {
        activations.extend(patterns.keys().cloned());
    }

    if let Some(remediation) = lang_def.remediation.as_ref() {
        activations.extend(remediation.keys().cloned());
    }

    if let Some(reports) = lang_def.reports.as_ref() {
        activations.extend(reports.keys().cloned());
    }

    activations.into_iter().collect()
}

fn generated_language_count(language_definitions: &str) -> usize {
    language_definitions
        .lines()
        .filter_map(|line| {
            let trimmed = line.trim();
            if !trimmed.starts_with('[') || trimmed.starts_with("[[") {
                return None;
            }
            let table = trimmed.trim_start_matches('[').trim_end_matches(']');
            table
                .split_once('.')
                .map(|(language, _)| language.to_owned())
        })
        .collect::<BTreeSet<_>>()
        .len()
}

/// Render the full `CONVENTIONS.toml` text: header comments, language
/// definitions, then every rule annotated with per-field comments.
fn render_conventions(generated: &GeneratedConventions) -> String {
    let mut out = String::from(HEADER);
    let _ = writeln!(
        out,
        "# Language definitions: bundled templates for detected source languages."
    );
    out.push_str(generated.language_definitions.trim_end());
    out.push_str("\n\n");
    let _ = writeln!(
        out,
        "# Rules: path-scoped activations of the tools declared above."
    );
    for rule in &generated.rules {
        render_rule(&mut out, rule);
    }
    out
}

/// Render one rule as a commented TOML table.
fn render_rule(out: &mut String, rule: &GeneratedRule) {
    let _ = writeln!(out, "[{}]", rule.name);
    let _ = writeln!(out, "# tools: mutation tools that activate this rule.");
    let _ = writeln!(out, "tools = {}", toml_str_array(&rule.tools));
    let _ = writeln!(
        out,
        "# paths: globs matched against the modified file path (workspace-relative)."
    );
    let _ = writeln!(out, "paths = {}", toml_str_array(&rule.paths));
    if let Some((limit, handling)) = rule.loc {
        let _ = writeln!(
            out,
            "# loc.limit: max code lines (counted by tokei) before the file-length check fires."
        );
        let _ = writeln!(
            out,
            "# loc.handling: \"advise\" emits required fix feedback; \"block\" emits a validation failure."
        );
        let _ = writeln!(
            out,
            "loc = {{ limit = {limit}, handling = \"{handling}\" }}"
        );
    } else {
        let _ = writeln!(out, "# loc: omitted — this rule has no file-length check.");
    }
    let _ = writeln!(
        out,
        "# tool activations: explicit tool names with lifecycle trigger and required-feedback handling."
    );
    for tool in &rule.activations {
        let _ = writeln!(out, "{tool} = {{ on = \"tool\", handling = \"advise\" }}");
    }
    let _ = writeln!(
        out,
        "# priority: tiebreaker when LOC limits collide on one file (higher wins; default 0)."
    );
    if rule.priority != 0 {
        let _ = writeln!(out, "priority = {}", rule.priority);
    }
    if rule.lsp_diagnostics {
        let _ = writeln!(out);
        let _ = writeln!(out, "[{}.lsp.diagnostics]", rule.name);
        let _ = writeln!(
            out,
            "# LSP diagnostics use the shared language-server check path; findings are required fix feedback."
        );
        let _ = writeln!(out, "handling = \"advise\"");
    }
    let _ = writeln!(out);
}

/// Format a list of strings as a TOML inline array of quoted strings.
fn toml_str_array(items: &[String]) -> String {
    let inner = items
        .iter()
        .map(|s| format!("\"{s}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!("[{inner}]")
}

#[cfg(test)]
mod tests {
    use super::*;
    use norn::tools::conventions::ConventionsConfig;
    use serial_test::serial;
    use std::{error::Error, fs, io};
    use tempfile::tempdir;

    fn touch(dir: &Path, rel: &str) -> io::Result<()> {
        let path = dir.join(rel);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&path, "// sample\n")
    }

    fn missing(name: &'static str) -> io::Error {
        io::Error::new(io::ErrorKind::NotFound, name)
    }

    // -- R2: project file tree scanning --

    #[test]
    fn scan_counts_extensions_and_skips_excluded_dirs() -> Result<(), Box<dyn Error>> {
        let dir = tempdir()?;
        let root = dir.path();
        touch(root, "a.rs")?;
        touch(root, "src/b.rs")?;
        touch(root, "src/nested/c.rs")?;
        touch(root, "x.ts")?;
        touch(root, "src/y.ts")?;
        // Excluded: must not contribute.
        touch(root, "target/built.rs")?;
        touch(root, "node_modules/dep.ts")?;
        touch(root, ".git/config.rs")?;
        touch(root, ".hidden/secret.rs")?;

        let counts = scan_project_extensions(root)?;
        assert_eq!(counts.get("rs"), Some(&3));
        assert_eq!(counts.get("ts"), Some(&2));
        Ok(())
    }

    // -- R1: language definition emission + PATH augmentation --

    #[test]
    fn language_definitions_emit_detected_templates_only() -> Result<(), Box<dyn Error>> {
        let mut exts = BTreeMap::new();
        exts.insert("rs".to_owned(), 1);
        exts.insert("ts".to_owned(), 1);
        let generated = generate_conventions(&exts, &|_| false)?;
        let config = ConventionsConfig::load_from_str(&generated.language_definitions)?;

        assert!(config.lang_def("rust").is_some());
        assert!(config.lang_def("typescript").is_some());
        assert!(config.lang_def("python").is_none());
        let rust = config
            .lang_def("rust")
            .ok_or_else(|| missing("rust lang def"))?;
        // Rust runs clippy as a subprocess, not via rust-analyzer's LSP check,
        // so the bundled template intentionally declares no `[rust.lsp]`.
        assert!(rust.lsp.is_none());
        assert!(rust.diagnostics.is_some());
        assert!(rust.patterns.is_some());
        assert!(rust.remediation.is_some());
        let typescript = config
            .lang_def("typescript")
            .ok_or_else(|| missing("typescript lang def"))?;
        assert!(typescript.lsp.is_some());
        assert!(typescript.diagnostics.is_some());
        assert!(typescript.patterns.is_some());
        Ok(())
    }

    #[test]
    fn mocked_mypy_available_appears_in_python_diagnostics() -> Result<(), Box<dyn Error>> {
        let mut exts = BTreeMap::new();
        exts.insert("py".to_owned(), 1);
        let probe = |tool: &str| tool == "mypy";
        let generated = generate_conventions(&exts, &probe)?;
        let config = ConventionsConfig::load_from_str(&generated.language_definitions)?;
        let python = config
            .lang_def("python")
            .ok_or_else(|| missing("python lang def"))?;
        let diagnostics = python
            .diagnostics
            .as_ref()
            .ok_or_else(|| missing("python diagnostics"))?;

        assert!(diagnostics.contains_key("mypy"));
        assert!(!diagnostics.contains_key("ruff"));
        Ok(())
    }

    #[test]
    fn mocked_eslint_available_appears_in_typescript_diagnostics() -> Result<(), Box<dyn Error>> {
        let mut exts = BTreeMap::new();
        exts.insert("ts".to_owned(), 1);
        let probe = |tool: &str| tool == "eslint" || tool == "biome";
        let generated = generate_conventions(&exts, &probe)?;
        let config = ConventionsConfig::load_from_str(&generated.language_definitions)?;
        let typescript = config
            .lang_def("typescript")
            .ok_or_else(|| missing("typescript lang def"))?;
        let diagnostics = typescript
            .diagnostics
            .as_ref()
            .ok_or_else(|| missing("typescript diagnostics"))?;

        assert!(diagnostics.contains_key("biome"));
        assert!(diagnostics.contains_key("eslint"));
        Ok(())
    }

    // -- R2/R3: rule generation from language definitions, without adapter probes --

    #[test]
    fn generation_emits_only_detected_languages_with_correct_defaults() -> Result<(), Box<dyn Error>>
    {
        let mut exts = BTreeMap::new();
        for ext in ["rs", "ts", "py", "go", "gleam"] {
            exts.insert(ext.to_owned(), 1);
        }
        let probe = |_: &str| false;
        let generated = generate_conventions(&exts, &probe)?;

        let general = generated
            .rules
            .iter()
            .find(|rule| rule.name == "rust-general")
            .ok_or_else(|| missing("rust-general"))?;
        assert_eq!(general.loc, Some((500, "advise")));
        assert_eq!(general.priority, 0);
        assert_eq!(general.tools, default_tools());
        assert!(!general.lsp_diagnostics);
        assert!(general.activations.iter().any(|tool| tool == "clippy"));
        assert!(general.activations.iter().any(|tool| tool == "rustfmt"));
        assert!(
            general
                .activations
                .iter()
                .any(|tool| tool == "todo-markers")
        );

        let entrypoints = generated
            .rules
            .iter()
            .find(|rule| rule.name == "rust-entrypoints")
            .ok_or_else(|| missing("rust-entrypoints"))?;
        assert_eq!(entrypoints.loc, Some((200, "advise")));
        assert_eq!(entrypoints.priority, 10);
        assert!(!entrypoints.lsp_diagnostics);
        assert!(entrypoints.activations.iter().any(|tool| tool == "clippy"));

        let typescript = generated
            .rules
            .iter()
            .find(|rule| rule.name == "typescript-general")
            .ok_or_else(|| missing("typescript-general"))?;
        assert_eq!(typescript.loc, Some((400, "advise")));
        assert_eq!(
            typescript.paths,
            vec!["*.ts".to_owned(), "**/*.ts".to_owned()]
        );
        assert!(typescript.activations.iter().any(|tool| tool == "biome"));
        assert!(
            typescript
                .activations
                .iter()
                .any(|tool| tool == "ts_ignore")
        );

        let python = generated
            .rules
            .iter()
            .find(|rule| rule.name == "python-general")
            .ok_or_else(|| missing("python-general"))?;
        assert_eq!(python.loc, Some((300, "advise")));

        assert!(generated.rules.iter().any(|rule| rule.name == "go-general"));
        assert!(
            generated
                .rules
                .iter()
                .any(|rule| rule.name == "gleam-general")
        );
        Ok(())
    }

    #[test]
    fn no_definitions_or_rules_for_absent_languages() -> Result<(), Box<dyn Error>> {
        let mut exts = BTreeMap::new();
        exts.insert("rs".to_owned(), 1);
        let probe = |_: &str| false;
        let generated = generate_conventions(&exts, &probe)?;
        let config = ConventionsConfig::load_from_str(&generated.language_definitions)?;

        assert!(config.lang_def("rust").is_some());
        assert!(
            generated
                .rules
                .iter()
                .any(|rule| rule.name == "rust-general")
        );
        assert!(config.lang_def("python").is_none());
        assert!(config.lang_def("typescript").is_none());
        assert!(
            !generated
                .rules
                .iter()
                .any(|rule| rule.name == "python-general")
        );
        assert!(
            !generated
                .rules
                .iter()
                .any(|rule| rule.name == "typescript-general")
        );
        Ok(())
    }

    // -- R4: CONVENTIONS.toml output with comments + round-trip --

    #[test]
    fn generated_file_round_trips_through_loader() -> Result<(), Box<dyn Error>> {
        let mut exts = BTreeMap::new();
        for ext in ["rs", "ts", "py"] {
            exts.insert(ext.to_owned(), 1);
        }
        let probe = |tool: &str| tool == "eslint" || tool == "mypy";
        let generated = generate_conventions(&exts, &probe)?;
        let rendered = render_conventions(&generated);

        assert!(rendered.contains("# CONVENTIONS.toml"));
        assert!(rendered.contains("# tools:"));
        assert!(rendered.contains("not optional guidance"));
        assert!(rendered.contains("required-feedback handling"));
        assert!(!rendered.contains("advise_on"));
        assert!(!rendered.contains("block_on"));
        assert!(!rendered.contains("bypass_detection"));
        assert!(rendered.contains("# priority:"));

        let dir = tempdir()?;
        let path = dir.path().join("CONVENTIONS.toml");
        fs::write(&path, &rendered)?;

        let config = ConventionsConfig::load(&path)?;
        assert!(config.lang_defs().contains_key("rust"));
        assert!(config.lang_defs().contains_key("typescript"));
        assert!(config.lang_defs().contains_key("python"));
        assert_eq!(config.rules().len(), generated.rules.len());
        let general = config
            .rule("rust-general")
            .ok_or_else(|| missing("rust-general"))?;
        let loc = general
            .rule
            .loc
            .as_ref()
            .ok_or_else(|| missing("loc present"))?;
        assert_eq!(loc.limit, 500);
        assert!(general.rule.lsp.is_none());
        assert!(general.rule.activations.contains_key("clippy"));
        assert!(general.rule.activations.contains_key("rustfmt"));
        assert!(general.rule.activations.contains_key("todo-markers"));
        assert!(config.lookup_tool("typescript", "eslint").is_some());
        assert!(config.lookup_tool("python", "mypy").is_some());
        let entrypoints = config
            .rule("rust-entrypoints")
            .ok_or_else(|| missing("rust-entrypoints"))?;
        assert_eq!(entrypoints.rule.priority, 10);
        Ok(())
    }

    // -- R7: safe write flow --

    /// Save the current directory, switch into `dir`, run `f`, then restore.
    fn with_cwd<R>(dir: &Path, f: impl FnOnce() -> R) -> io::Result<R> {
        let original = std::env::current_dir()?;
        std::env::set_current_dir(dir)?;
        let result = f();
        std::env::set_current_dir(original)?;
        Ok(result)
    }

    #[test]
    #[serial]
    fn existing_default_file_is_not_overwritten() -> Result<(), Box<dyn Error>> {
        let dir = tempdir()?;
        let path = dir.path().join(DEFAULT_FILENAME);
        let sentinel = "# do not touch\n";
        fs::write(&path, sentinel)?;

        let code = with_cwd(dir.path(), || run_conventions(None))?;
        assert_eq!(code, ExitCode::Success);
        assert_eq!(fs::read_to_string(&path)?, sentinel);
        Ok(())
    }

    #[test]
    #[serial]
    fn output_flag_writes_alternate_path_even_when_default_exists() -> Result<(), Box<dyn Error>> {
        let dir = tempdir()?;
        fs::write(dir.path().join(DEFAULT_FILENAME), "# existing\n")?;
        touch(dir.path(), "lib.rs")?;

        let code = with_cwd(dir.path(), || {
            run_conventions(Some(PathBuf::from("alt.toml")))
        })?;
        assert_eq!(code, ExitCode::Success);

        let alt = dir.path().join("alt.toml");
        assert!(alt.exists());
        ConventionsConfig::load(&alt)?;
        // The default file is left untouched.
        assert_eq!(
            fs::read_to_string(dir.path().join(DEFAULT_FILENAME))?,
            "# existing\n"
        );
        Ok(())
    }

    #[test]
    #[serial]
    fn end_to_end_generation_from_sample_sources() -> Result<(), Box<dyn Error>> {
        let dir = tempdir()?;
        touch(dir.path(), "src/lib.rs")?;
        touch(dir.path(), "src/main.rs")?;
        touch(dir.path(), "web/app.ts")?;

        let code = with_cwd(dir.path(), || run_conventions(None))?;
        assert_eq!(code, ExitCode::Success);

        let path = dir.path().join(DEFAULT_FILENAME);
        assert!(path.exists());
        let config = ConventionsConfig::load(&path)?;
        assert!(config.lang_defs().contains_key("rust"));
        assert!(config.lang_defs().contains_key("typescript"));
        assert!(config.rule("rust-general").is_some());
        assert!(config.rule("typescript-general").is_some());
        let rust = config
            .rule("rust-general")
            .ok_or_else(|| missing("rust-general"))?;
        assert!(rust.rule.lsp.is_none());
        assert!(rust.rule.activations.contains_key("clippy"));
        assert!(rust.rule.activations.contains_key("rustfmt"));
        assert!(rust.rule.activations.contains_key("todo-markers"));
        let typescript = config
            .rule("typescript-general")
            .ok_or_else(|| missing("typescript-general"))?;
        assert!(typescript.rule.activations.contains_key("biome"));
        assert!(typescript.rule.activations.contains_key("ts_ignore"));
        Ok(())
    }
}
