//! `norn init conventions --upgrade` — migrate legacy convention groups
//! into the flat tool-activation rule format.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use diagnostics::conventions::ConventionsConfig;
use diagnostics::language_packs::{
    SUPPORTED_LANGUAGES, file_extension_to_language, template_for_language,
};
use toml::{Table, Value};

use crate::cli::ExitCode;

const DEFAULT_FILENAME: &str = "CONVENTIONS.toml";
const LANGUAGE_KEYS: &[&str] = &["lsp", "patterns", "diagnostics", "remediation", "reports"];
const HEADER: &str = "\
# CONVENTIONS.toml — migrated to flat tool activations.
# Generated by `norn init conventions --upgrade`.
# Review this output before replacing the original file.

";

#[derive(Debug, thiserror::Error)]
enum UpgradeError {
    #[error("failed to parse {path}: {source}")]
    Parse {
        path: String,
        source: toml::de::Error,
    },
    #[error("{rule}: legacy convention groups must include both `tools` and `paths` to migrate")]
    MissingRuleShape { rule: String },
    #[error("{rule}: `{field}` must be an array of strings")]
    StringArray { rule: String, field: &'static str },
    #[error("renaming rule `{original}` to `{target}` would overwrite an existing migrated rule")]
    RuleNameCollision { original: String, target: String },
    #[error("migrated conventions did not pass production validation: {0}")]
    Validation(diagnostics::conventions::ConventionsError),
    #[error("failed to read {path}: {source}")]
    Read {
        path: String,
        source: std::io::Error,
    },
    #[error("failed to write {path}: {source}")]
    Write {
        path: String,
        source: std::io::Error,
    },
    #[error("cannot resolve working directory: {0}")]
    Cwd(std::io::Error),
}

/// Run `norn init conventions --upgrade`.
pub fn run_upgrade(input: Option<PathBuf>, output: Option<PathBuf>) -> ExitCode {
    match run_upgrade_inner(input, output) {
        Ok(()) => ExitCode::Success,
        Err(error) => {
            eprintln!("norn: {error}");
            ExitCode::AgentError
        }
    }
}

fn run_upgrade_inner(input: Option<PathBuf>, output: Option<PathBuf>) -> Result<(), UpgradeError> {
    let cwd = std::env::current_dir().map_err(UpgradeError::Cwd)?;
    let input_path = resolve_path(
        &cwd,
        input.unwrap_or_else(|| PathBuf::from(DEFAULT_FILENAME)),
    );
    let contents = {
        let _descriptor_permit = norn::resource::acquire_filesystem_operation()
            .map_err(std::io::Error::other)
            .map_err(|source| UpgradeError::Read {
                path: input_path.display().to_string(),
                source,
            })?;
        std::fs::read_to_string(&input_path).map_err(|source| UpgradeError::Read {
            path: input_path.display().to_string(),
            source,
        })?
    };

    let rendered = upgrade_conventions(&contents, &input_path.display().to_string())?;

    if let Some(path) = output {
        let target = resolve_path(&cwd, path);
        let _descriptor_permit = norn::resource::acquire_filesystem_operation()
            .map_err(std::io::Error::other)
            .map_err(|source| UpgradeError::Write {
                path: target.display().to_string(),
                source,
            })?;
        std::fs::write(&target, rendered).map_err(|source| UpgradeError::Write {
            path: target.display().to_string(),
            source,
        })?;
        println!("Wrote migrated conventions to {}.", target.display());
    } else {
        print!("{rendered}");
    }

    Ok(())
}

fn resolve_path(cwd: &Path, path: PathBuf) -> PathBuf {
    if path.is_absolute() {
        path
    } else {
        cwd.join(path)
    }
}

fn upgrade_conventions(contents: &str, source_name: &str) -> Result<String, UpgradeError> {
    let raw: Table = toml::from_str(contents).map_err(|source| UpgradeError::Parse {
        path: source_name.to_owned(),
        source,
    })?;
    let mut language_defs = extract_language_defs(&raw);
    let existing_language_names = language_defs.keys().cloned().collect::<BTreeSet<_>>();
    let mut detected_languages = BTreeSet::new();
    let mut rules = BTreeMap::new();

    for (name, value) in raw {
        let Value::Table(table) = value else {
            continue;
        };
        if is_rule_or_legacy_table(&table) {
            let has_language_def = language_defs.contains_key(&name);
            let detected_language = detect_language(&name, &table, &existing_language_names);
            if let Some(language) = detected_language.as_deref() {
                detected_languages.insert(language.to_owned());
            }
            let rule_name =
                if detected_language.as_deref() == Some(name.as_str()) || has_language_def {
                    format!("{name}-general")
                } else {
                    name.clone()
                };
            let migrated_rule =
                migrate_rule(&name, table, detected_language.as_deref(), has_language_def)?;
            insert_rule(&mut rules, &name, rule_name, migrated_rule)?;
        }
    }

    for language in detected_languages {
        merge_template_language_def(&mut language_defs, &language)?;
    }

    let body = render_document(&language_defs, &rules);
    let rendered = format!("{HEADER}{body}");
    ConventionsConfig::load_from_str(&rendered).map_err(UpgradeError::Validation)?;
    Ok(rendered)
}

/// Render the migrated document in the canonical inline-table style used by
/// hand-written `CONVENTIONS.toml` files and `norn init conventions`.
///
/// `toml::to_string_pretty` expands every nested tool table into its own
/// `[lang.category.tool]` header, which diverges from the inline
/// `tool = { ... }` form the rest of the system emits. This renderer keeps
/// each tool definition and rule activation inline by leaning on
/// [`toml::Value`]'s `Display`, which formats tables inline and escapes leaf
/// values correctly.
fn render_document(
    language_defs: &BTreeMap<String, Table>,
    rules: &BTreeMap<String, Table>,
) -> String {
    let mut out = String::new();
    for (language, def) in language_defs {
        render_language_def(&mut out, language, def);
    }
    for (name, rule) in rules {
        render_rule(&mut out, name, rule);
    }
    out
}

/// Render a language definition as `[lang.category]` sections, one inline
/// `tool = { ... }` entry per declared tool. Categories follow
/// [`LANGUAGE_KEYS`] order so output is deterministic.
fn render_language_def(out: &mut String, language: &str, def: &Table) {
    for category in LANGUAGE_KEYS {
        let Some(Value::Table(entries)) = def.get(*category) else {
            continue;
        };
        let _ = writeln!(out, "[{language}.{category}]");
        for (key, value) in entries {
            let _ = writeln!(out, "{key} = {value}");
        }
        out.push('\n');
    }
}

/// Render a migrated rule as a `[name]` section. Structural keys
/// (`tools`, `paths`, `priority`, `loc`) lead, then tool activations follow
/// in deterministic order, every value rendered inline.
fn render_rule(out: &mut String, name: &str, rule: &Table) {
    const STRUCTURAL: &[&str] = &["tools", "paths", "priority", "loc"];
    let _ = writeln!(out, "[{name}]");
    for key in STRUCTURAL {
        if let Some(value) = rule.get(*key) {
            let _ = writeln!(out, "{key} = {value}");
        }
    }
    for (key, value) in rule {
        if STRUCTURAL.contains(&key.as_str()) {
            continue;
        }
        let _ = writeln!(out, "{key} = {value}");
    }
    out.push('\n');
}

fn extract_language_defs(raw: &Table) -> BTreeMap<String, Table> {
    let mut language_defs = BTreeMap::new();
    for (name, value) in raw {
        let Value::Table(table) = value else {
            continue;
        };
        if has_rule_shape(table) && !SUPPORTED_LANGUAGES.iter().any(|language| language == name) {
            continue;
        }
        let mut def = Table::new();
        for key in LANGUAGE_KEYS {
            if let Some(value) = table.get(*key) {
                def.insert((*key).to_owned(), value.clone());
            }
        }
        if !def.is_empty() {
            language_defs.insert(name.clone(), def);
        }
    }
    language_defs
}

fn has_rule_shape(table: &Table) -> bool {
    table.contains_key("tools") && table.contains_key("paths")
}

fn is_rule_or_legacy_table(table: &Table) -> bool {
    table.contains_key("tools")
        || table.contains_key("paths")
        || table.contains_key("advise_on")
        || table.contains_key("block_on")
        || table.contains_key("bypass_detection")
}

fn insert_rule(
    rules: &mut BTreeMap<String, Table>,
    source_name: &str,
    rule_name: String,
    rule: Table,
) -> Result<(), UpgradeError> {
    if rules.insert(rule_name.clone(), rule).is_some() {
        return Err(UpgradeError::RuleNameCollision {
            original: source_name.to_owned(),
            target: rule_name,
        });
    }
    Ok(())
}

fn migrate_rule(
    name: &str,
    table: Table,
    detected_language: Option<&str>,
    strip_language_keys: bool,
) -> Result<Table, UpgradeError> {
    if !table.contains_key("tools") || !table.contains_key("paths") {
        return Err(UpgradeError::MissingRuleShape {
            rule: name.to_owned(),
        });
    }

    let advise_on = string_array(name, table.get("advise_on"), "advise_on")?;
    let block_on = string_array(name, table.get("block_on"), "block_on")?;
    let bypass_detection = table
        .get("bypass_detection")
        .and_then(Value::as_bool)
        .unwrap_or(false);

    let mut rule = Table::new();
    for (key, value) in table {
        if is_legacy_key(&key) || (strip_language_keys && LANGUAGE_KEYS.contains(&key.as_str())) {
            continue;
        }
        rule.insert(key, value);
    }

    for tool in advise_on {
        insert_activation(&mut rule, &tool, "advise");
    }
    for tool in block_on {
        insert_activation(&mut rule, &tool, "block");
    }

    if bypass_detection && let Some(language) = detected_language {
        for pattern in bundled_pattern_names(language)? {
            insert_activation(&mut rule, &pattern, "advise");
        }
    }

    Ok(rule)
}

fn is_legacy_key(key: &str) -> bool {
    matches!(key, "advise_on" | "block_on" | "bypass_detection")
}

fn insert_activation(rule: &mut Table, tool: &str, handling: &str) {
    let mut activation = Table::new();
    activation.insert("on".to_owned(), Value::String("tool".to_owned()));
    activation.insert("handling".to_owned(), Value::String(handling.to_owned()));
    rule.insert(tool.to_owned(), Value::Table(activation));
}

fn string_array(
    rule: &str,
    value: Option<&Value>,
    field: &'static str,
) -> Result<Vec<String>, UpgradeError> {
    let Some(value) = value else {
        return Ok(Vec::new());
    };
    let Some(items) = value.as_array() else {
        return Err(UpgradeError::StringArray {
            rule: rule.to_owned(),
            field,
        });
    };
    let mut strings = Vec::new();
    for item in items {
        let Some(item) = item.as_str() else {
            return Err(UpgradeError::StringArray {
                rule: rule.to_owned(),
                field,
            });
        };
        strings.push(item.to_owned());
    }
    Ok(strings)
}

fn bundled_pattern_names(language: &str) -> Result<Vec<String>, UpgradeError> {
    let Some(template) = template_for_language(language) else {
        return Ok(Vec::new());
    };
    let template: Table = toml::from_str(template).map_err(|source| UpgradeError::Parse {
        path: format!("bundled template `{language}`"),
        source,
    })?;
    let Some(Value::Table(language_table)) = template.get(language) else {
        return Ok(Vec::new());
    };
    let Some(Value::Table(patterns)) = language_table.get("patterns") else {
        return Ok(Vec::new());
    };
    Ok(patterns.keys().cloned().collect())
}

fn detect_language(
    name: &str,
    table: &Table,
    existing_languages: &BTreeSet<String>,
) -> Option<String> {
    if is_known_language(name, existing_languages) {
        return Some(name.to_owned());
    }
    if let Some((prefix, _)) = name.split_once('-')
        && is_known_language(prefix, existing_languages)
    {
        return Some(prefix.to_owned());
    }
    paths_languages(table).into_iter().next()
}

fn is_known_language(name: &str, existing_languages: &BTreeSet<String>) -> bool {
    existing_languages.contains(name)
        || SUPPORTED_LANGUAGES.iter().any(|language| language == &name)
}

fn paths_languages(table: &Table) -> BTreeSet<String> {
    let mut languages = BTreeSet::new();
    if let Some(Value::Array(paths)) = table.get("paths") {
        for path in paths {
            if let Some(path) = path.as_str()
                && let Some(extension) = concrete_extension(path)
                && let Some(language) = file_extension_to_language(&extension)
            {
                languages.insert(language.to_owned());
            }
        }
    }
    languages
}

fn concrete_extension(path: &str) -> Option<String> {
    let segment = path
        .rsplit(['/', '\\'])
        .next()
        .map_or(path, |segment| segment);
    let mut languages = BTreeSet::new();
    collect_extensions(segment, &mut languages);
    languages.into_iter().next()
}

fn collect_extensions(pattern: &str, extensions: &mut BTreeSet<String>) {
    if let Some((prefix, choices, suffix)) = split_brace_choices(pattern) {
        for choice in choices.split(',') {
            let expanded = format!("{prefix}{choice}{suffix}");
            collect_extensions(&expanded, extensions);
        }
        return;
    }

    let Some((_, extension)) = pattern.rsplit_once('.') else {
        return;
    };
    let extension = extension
        .trim_end_matches('}')
        .trim_end_matches(']')
        .trim_end_matches(')')
        .trim_end_matches('*')
        .trim_end_matches('?')
        .to_ascii_lowercase();
    if !extension.is_empty()
        && !extension.contains('*')
        && !extension.contains('?')
        && !extension.contains('{')
        && !extension.contains(',')
    {
        extensions.insert(extension);
    }
}

fn split_brace_choices(pattern: &str) -> Option<(&str, &str, &str)> {
    let start = pattern.find('{')?;
    let rest = &pattern[start + 1..];
    let end = rest.find('}')?;
    let choices = &rest[..end];
    if choices.is_empty() || !choices.contains(',') {
        return None;
    }
    Some((&pattern[..start], choices, &rest[end + 1..]))
}

fn merge_template_language_def(
    language_defs: &mut BTreeMap<String, Table>,
    language: &str,
) -> Result<(), UpgradeError> {
    let Some(template) = template_for_language(language) else {
        return Ok(());
    };
    let template: Table = toml::from_str(template).map_err(|source| UpgradeError::Parse {
        path: format!("bundled template `{language}`"),
        source,
    })?;
    let Some(Value::Table(template_def)) = template.get(language) else {
        return Ok(());
    };
    let target = language_defs.entry(language.to_owned()).or_default();
    merge_language_table(target, template_def);
    Ok(())
}

fn merge_language_table(target: &mut Table, template: &Table) {
    for (key, template_value) in template {
        match (target.get_mut(key), template_value) {
            (Some(Value::Table(target_table)), Value::Table(template_table))
                if is_map_language_category(key) =>
            {
                for (tool, value) in template_table {
                    target_table
                        .entry(tool.clone())
                        .or_insert_with(|| value.clone());
                }
            }
            (Some(_), _) => {}
            (None, _) => {
                target.insert(key.clone(), template_value.clone());
            }
        }
    }
}

fn is_map_language_category(key: &str) -> bool {
    matches!(key, "patterns" | "diagnostics" | "remediation" | "reports")
}

#[cfg(test)]
#[path = "upgrade_tests.rs"]
mod upgrade_tests;
