//! JSON Schema generation for enums.
//!
//! Handles the four serde enum representations relevant to tool schemas:
//!
//! * **String enum** — every variant is `Unit` and there is no `tag` /
//!   `untagged` attribute. Emits `{"type": "string", "enum": [...]}`.
//! * **Internally tagged** — `#[serde(tag = "t")]`. Emits a root
//!   `type: "object"` with `oneOf` of objects each carrying `t` as a const
//!   discriminator alongside the variant's named fields.
//! * **Adjacently tagged** — `#[serde(tag = "t", content = "c")]`. Emits a
//!   root `type: "object"` with `oneOf` of objects each with the tag as a
//!   const and (for data-bearing variants) the variant's data nested under
//!   `c`.
//! * **Untagged** — `#[serde(untagged)]`. Emits `oneOf` of the per-variant
//!   data schemas with no discriminator and no root `type` (variants may be
//!   non-objects).
//!
//! Tagged representations declare `type: "object"` at the root because
//! providers (`OpenAI` in particular) reject function-parameter schemas
//! whose root is not an object schema; every tagged variant is an object,
//! so the declaration is always sound.
//!
//! Tuple variants (`Foo(String)`) are rejected at parse time. External tagging
//! (data variants without any of the three serde attrs) produces a spanned
//! compile error suggesting the user pick a representation, per the
//! NTM-002 brief.

use proc_macro2::TokenStream;
use quote::quote;
use syn::Error;

use super::parse::{EnumRepresentation, ParsedEnum, ParsedVariant, VariantFields};
use super::rename::RenameRule;
use super::schema::build_field_props;

/// Emits the full `impl` block exposing `json_schema()` for the parsed enum,
/// dispatching to the right schema shape for its representation.
pub(super) fn build_enum_impl(parsed: &ParsedEnum) -> syn::Result<TokenStream> {
    let body = match &parsed.representation {
        EnumRepresentation::Default => build_string_enum(parsed)?,
        EnumRepresentation::InternallyTagged { tag } => build_internally_tagged(parsed, tag)?,
        EnumRepresentation::Adjacent { tag, content } => build_adjacent(parsed, tag, content)?,
        EnumRepresentation::Untagged => build_untagged(parsed)?,
    };
    let ident = &parsed.ident;
    Ok(quote! {
        impl #ident {
            /// JSON Schema describing this type's model-facing arguments,
            /// generated by `#[derive(ToolArgs)]`.
            pub fn json_schema() -> ::serde_json::Value {
                #body
            }
        }
    })
}

/// Builds the body for a string-enum: `{"type": "string", "enum": [...]}`,
/// rejecting any variant that carries data (that would be external tagging,
/// which we do not generate).
fn build_string_enum(parsed: &ParsedEnum) -> syn::Result<TokenStream> {
    for variant in &parsed.variants {
        if !matches!(variant.fields, VariantFields::Unit) {
            return Err(Error::new_spanned(
                &variant.ident,
                "ToolArgs: data-bearing enum variants require a serde representation \
                 attribute — add #[serde(tag = \"...\")], #[serde(tag = \"t\", content = \"c\")], \
                 or #[serde(untagged)] on the enum",
            ));
        }
    }
    let wire_names: Vec<String> = parsed
        .variants
        .iter()
        .map(|v| wire_name(v, parsed.rename_all))
        .collect();
    let description = string_enum_description(parsed, &wire_names);
    if description.is_empty() {
        Ok(quote! {
            ::serde_json::json!({
                "type": "string",
                "enum": [ #( #wire_names ),* ]
            })
        })
    } else {
        Ok(quote! {
            ::serde_json::json!({
                "type": "string",
                "enum": [ #( #wire_names ),* ],
                "description": #description
            })
        })
    }
}

/// Composes the description for a string enum from the container doc comment
/// and per-variant entries. Variants without docs are skipped. Returns the
/// empty string when there is nothing to write.
fn string_enum_description(parsed: &ParsedEnum, wire_names: &[String]) -> String {
    let mut parts = Vec::new();
    if !parsed.description.is_empty() {
        parts.push(parsed.description.clone());
    }
    for (variant, name) in parsed.variants.iter().zip(wire_names) {
        if !variant.description.is_empty() {
            parts.push(format!("{name}: {}", variant.description));
        }
    }
    parts.join(" ")
}

/// Builds the body for an internally-tagged enum. Each variant becomes an
/// object schema with the tag field as a `const` plus any named fields the
/// variant carries, and the variant's doc comment as its `description`.
fn build_internally_tagged(parsed: &ParsedEnum, tag: &str) -> syn::Result<TokenStream> {
    let mut variant_schemas = Vec::with_capacity(parsed.variants.len());
    for variant in &parsed.variants {
        let wire = wire_name(variant, parsed.rename_all);
        let (prop_names, prop_schemas, mut required) = match &variant.fields {
            VariantFields::Unit => (Vec::new(), Vec::new(), Vec::new()),
            VariantFields::Named(fields) => build_field_props(fields)?,
        };
        // Tag is always present and always required, in addition to whatever
        // the variant's named fields require.
        required.insert(0, tag.to_string());
        let tag_lit = tag.to_string();
        let description = variant_description_tokens(&variant.description);
        variant_schemas.push(quote! {
            ::serde_json::json!({
                "type": "object",
                "properties": {
                    #tag_lit : { "const": #wire },
                    #( #prop_names : #prop_schemas ),*
                },
                "required": [ #( #required ),* ],
                "additionalProperties": false
                #description
            })
        });
    }
    Ok(wrap_one_of(parsed, &variant_schemas, RootType::Object))
}

/// Builds the body for an adjacently-tagged enum. Unit variants get just the
/// tag field; data-bearing variants get both the tag and `content` field, with
/// the content carrying the variant's named-field object schema.
fn build_adjacent(parsed: &ParsedEnum, tag: &str, content: &str) -> syn::Result<TokenStream> {
    let mut variant_schemas = Vec::with_capacity(parsed.variants.len());
    for variant in &parsed.variants {
        let wire = wire_name(variant, parsed.rename_all);
        let tag_lit = tag.to_string();
        let content_lit = content.to_string();
        let description = variant_description_tokens(&variant.description);
        let schema = match &variant.fields {
            VariantFields::Unit => quote! {
                ::serde_json::json!({
                    "type": "object",
                    "properties": { #tag_lit : { "const": #wire } },
                    "required": [ #tag_lit ],
                    "additionalProperties": false
                    #description
                })
            },
            VariantFields::Named(fields) => {
                let inner = variant_named_object(fields, "")?;
                quote! {
                    ::serde_json::json!({
                        "type": "object",
                        "properties": {
                            #tag_lit : { "const": #wire },
                            #content_lit : #inner
                        },
                        "required": [ #tag_lit, #content_lit ],
                        "additionalProperties": false
                        #description
                    })
                }
            }
        };
        variant_schemas.push(schema);
    }
    Ok(wrap_one_of(parsed, &variant_schemas, RootType::Object))
}

/// Builds the body for an untagged enum. Each variant emits its data schema
/// directly into the `oneOf` array with no discriminator; the variant's doc
/// comment rides the data schema itself.
fn build_untagged(parsed: &ParsedEnum) -> syn::Result<TokenStream> {
    let mut variant_schemas = Vec::with_capacity(parsed.variants.len());
    for variant in &parsed.variants {
        let wire = wire_name(variant, parsed.rename_all);
        let description = variant_description_tokens(&variant.description);
        let schema = match &variant.fields {
            VariantFields::Unit => quote! {
                ::serde_json::json!({ "type": "string", "const": #wire #description })
            },
            VariantFields::Named(fields) => variant_named_object(fields, &variant.description)?,
        };
        variant_schemas.push(schema);
    }
    Ok(wrap_one_of(parsed, &variant_schemas, RootType::Untyped))
}

/// Builds an object schema for a named-field variant payload: `type: object`
/// plus the field properties, `required` list, `additionalProperties:
/// false`, and the supplied description when non-empty.
fn variant_named_object(
    fields: &[super::parse::ParsedField],
    description: &str,
) -> syn::Result<TokenStream> {
    let (prop_names, prop_schemas, required) = build_field_props(fields)?;
    let description = variant_description_tokens(description);
    Ok(quote! {
        ::serde_json::json!({
            "type": "object",
            "properties": {
                #( #prop_names : #prop_schemas ),*
            },
            "required": [ #( #required ),* ],
            "additionalProperties": false
            #description
        })
    })
}

/// Tokens splicing `, "description": "..."` into a `json!` object literal,
/// or nothing when the variant has no doc comment.
fn variant_description_tokens(description: &str) -> TokenStream {
    if description.is_empty() {
        quote! {}
    } else {
        quote! { , "description": #description }
    }
}

/// Root schema shape for a `oneOf`-wrapped enum.
#[derive(Clone, Copy)]
enum RootType {
    /// Declare `type: "object"` at the root — sound for tagged
    /// representations where every variant is an object schema, and required
    /// by providers (`OpenAI` rejects function-parameter schemas whose root
    /// lacks `type: "object"`).
    Object,
    /// No root `type` — untagged variants may be non-objects.
    Untyped,
}

/// Wraps a list of variant schemas in `oneOf`, attaching the enum's container
/// doc-comment description when one is present and a root `type: "object"`
/// declaration when the representation guarantees object variants.
fn wrap_one_of(
    parsed: &ParsedEnum,
    variant_schemas: &[TokenStream],
    root_type: RootType,
) -> TokenStream {
    let type_tokens = match root_type {
        RootType::Object => quote! { "type": "object", },
        RootType::Untyped => quote! {},
    };
    let description = &parsed.description;
    if description.is_empty() {
        quote! {
            ::serde_json::json!({
                #type_tokens
                "oneOf": [ #( #variant_schemas ),* ]
            })
        }
    } else {
        quote! {
            ::serde_json::json!({
                #type_tokens
                "oneOf": [ #( #variant_schemas ),* ],
                "description": #description
            })
        }
    }
}

/// Resolves a variant's wire name. Precedence: per-variant `#[serde(rename =
/// "x")]` → container `#[serde(rename_all = "...")]` applied to the Rust
/// ident → the raw Rust ident.
fn wire_name(variant: &ParsedVariant, rename_all: Option<RenameRule>) -> String {
    if let Some(name) = &variant.rename {
        return name.clone();
    }
    let raw = variant.ident.to_string();
    match rename_all {
        Some(rule) => rule.apply(&raw),
        None => raw,
    }
}
