//! Generate Rust model metadata from the workspace model catalog asset.

use std::env;
use std::fmt;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

fn main() -> Result<(), String> {
    run().map_err(|err| format!("model catalog generation failed: {err}"))
}

fn run() -> Result<(), String> {
    let manifest_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").map_err(|err| format!("CARGO_MANIFEST_DIR: {err}"))?,
    );
    let asset_path = manifest_dir
        .parent()
        .and_then(Path::parent)
        .ok_or_else(|| {
            format!(
                "cannot resolve workspace root from {}",
                manifest_dir.display()
            )
        })?
        .join("assets")
        .join("models.json");
    println!("cargo:rerun-if-changed={}", asset_path.display());

    let raw = fs::read_to_string(&asset_path)
        .map_err(|err| format!("failed to read {}: {err}", asset_path.display()))?;
    let root: Value = serde_json::from_str(&raw)
        .map_err(|err| format!("invalid JSON in {}: {err}", asset_path.display()))?;

    let generated = generate_catalog(&root)?;
    let out_dir = PathBuf::from(env::var("OUT_DIR").map_err(|err| format!("OUT_DIR: {err}"))?);
    fs::write(out_dir.join("model_catalog_generated.rs"), generated)
        .map_err(|err| format!("failed to write generated catalog: {err}"))?;
    Ok(())
}

fn generate_catalog(root: &Value) -> Result<String, String> {
    let root = root
        .as_object()
        .ok_or_else(|| "root catalog must be an object".to_string())?;
    let schema_version = required_u64(root, "schema_version")?;
    let default = required_object(root, "default")?;
    let default_provider = required_str(default, "provider")?;
    let default_backend = required_str(default, "backend")?;
    let default_model = required_str(default, "model")?;

    let providers = required_object(root, "providers")?;
    if providers.get(default_provider).is_none() {
        return Err(format!(
            "default provider '{default_provider}' does not exist in providers"
        ));
    }

    let mut out = String::new();
    out.push_str("// @generated by crates/norn/build.rs from assets/models.json\n");
    out.push_str("pub const DEFAULT_PROVIDER: &str = ");
    out.push_str(&rust_str(default_provider));
    out.push_str(";\n");
    out.push_str("pub const DEFAULT_BACKEND: &str = ");
    out.push_str(&rust_str(default_backend));
    out.push_str(";\n");
    out.push_str("pub const DEFAULT_MODEL: &str = ");
    out.push_str(&rust_str(default_model));
    out.push_str(";\n\n");

    out.push_str("pub(super) const CATALOG: ModelCatalog = ModelCatalog {\n");
    push_fmt(
        &mut out,
        format_args!("    schema_version: {schema_version},\n"),
    )?;
    out.push_str("    default: ModelSelection {\n");
    push_fmt(
        &mut out,
        format_args!("        provider: {},\n", rust_str(default_provider)),
    )?;
    push_fmt(
        &mut out,
        format_args!("        backend: {},\n", rust_str(default_backend)),
    )?;
    push_fmt(
        &mut out,
        format_args!("        model: {},\n", rust_str(default_model)),
    )?;
    out.push_str("    },\n");
    out.push_str("    providers: &[\n");

    for (provider_id, provider) in providers {
        let provider_obj = provider
            .as_object()
            .ok_or_else(|| format!("providers.{provider_id} must be an object"))?;
        let display_name = required_str(provider_obj, "display_name")?;
        let backends = required_object(provider_obj, "backends")?;
        if provider_id == default_provider && backends.get(default_backend).is_none() {
            return Err(format!(
                "default backend '{default_backend}' does not exist under provider '{default_provider}'"
            ));
        }

        out.push_str("        ProviderEntry {\n");
        push_fmt(
            &mut out,
            format_args!("            id: {},\n", rust_str(provider_id)),
        )?;
        push_fmt(
            &mut out,
            format_args!("            display_name: {},\n", rust_str(display_name)),
        )?;
        out.push_str("            backends: &[\n");

        for (backend_id, backend) in backends {
            let backend_obj = backend.as_object().ok_or_else(|| {
                format!("providers.{provider_id}.backends.{backend_id} must be an object")
            })?;
            let backend_display_name = required_str(backend_obj, "display_name")?;
            let auth = required_str(backend_obj, "auth")?;
            let api_surface = required_str(backend_obj, "api_surface")?;
            let models = required_object(backend_obj, "models")?;
            if provider_id == default_provider
                && backend_id == default_backend
                && models.get(default_model).is_none()
            {
                return Err(format!(
                    "default model '{default_model}' does not exist under {default_provider}.{default_backend}"
                ));
            }

            out.push_str("                BackendEntry {\n");
            push_fmt(
                &mut out,
                format_args!("                    id: {},\n", rust_str(backend_id)),
            )?;
            push_fmt(
                &mut out,
                format_args!(
                    "                    display_name: {},\n",
                    rust_str(backend_display_name)
                ),
            )?;
            push_fmt(
                &mut out,
                format_args!("                    auth: {},\n", rust_str(auth)),
            )?;
            push_fmt(
                &mut out,
                format_args!(
                    "                    api_surface: {},\n",
                    rust_str(api_surface)
                ),
            )?;
            out.push_str("                    models: &[\n");

            for (model_id, model) in models {
                let model_obj = model.as_object().ok_or_else(|| {
                    format!("providers.{provider_id}.backends.{backend_id}.models.{model_id} must be an object")
                })?;
                out.push_str("                        ModelEntry {\n");
                push_fmt(
                    &mut out,
                    format_args!("                            id: {},\n", rust_str(model_id)),
                )?;
                push_fmt(
                    &mut out,
                    format_args!(
                        "                            display_name: {},\n",
                        rust_str(required_str(model_obj, "display_name")?)
                    ),
                )?;
                push_fmt(
                    &mut out,
                    format_args!(
                        "                            description: {},\n",
                        rust_str(required_str(model_obj, "description")?)
                    ),
                )?;
                push_fmt(
                    &mut out,
                    format_args!(
                        "                            context_window: {},\n",
                        rust_u64(required_u64(model_obj, "context_window")?)
                    ),
                )?;
                push_fmt(
                    &mut out,
                    format_args!(
                        "                            max_context_window: {},\n",
                        rust_u64(required_u64(model_obj, "max_context_window")?)
                    ),
                )?;
                push_fmt(
                    &mut out,
                    format_args!(
                        "                            default_reasoning_effort: {},\n",
                        rust_str(required_str(model_obj, "default_reasoning_effort")?)
                    ),
                )?;
                out.push_str("                            supported_reasoning_efforts: ");
                out.push_str(&rust_str_slice(required_str_array(
                    model_obj,
                    "supported_reasoning_efforts",
                )?));
                out.push_str(",\n");
                push_fmt(
                    &mut out,
                    format_args!(
                        "                            default_reasoning_summary: {},\n",
                        rust_str(required_str(model_obj, "default_reasoning_summary")?)
                    ),
                )?;
                push_fmt(
                    &mut out,
                    format_args!(
                        "                            supports_reasoning_summaries: {},\n",
                        required_bool(model_obj, "supports_reasoning_summaries")?
                    ),
                )?;
                out.push_str("                            service_tiers: &[\n");
                for tier in required_array(model_obj, "service_tiers")? {
                    let tier_obj = tier.as_object().ok_or_else(|| {
                        format!("{model_id}.service_tiers entries must be objects")
                    })?;
                    out.push_str("                                ServiceTierEntry {\n");
                    push_fmt(
                        &mut out,
                        format_args!(
                            "                                    id: {},\n",
                            rust_str(required_str(tier_obj, "id")?)
                        ),
                    )?;
                    push_fmt(
                        &mut out,
                        format_args!(
                            "                                    provider_value: {},\n",
                            rust_str(required_str(tier_obj, "provider_value")?)
                        ),
                    )?;
                    push_fmt(
                        &mut out,
                        format_args!(
                            "                                    display_name: {},\n",
                            rust_str(required_str(tier_obj, "display_name")?)
                        ),
                    )?;
                    push_fmt(
                        &mut out,
                        format_args!(
                            "                                    description: {},\n",
                            rust_str(required_str(tier_obj, "description")?)
                        ),
                    )?;
                    out.push_str("                                },\n");
                }
                out.push_str("                            ],\n");
                push_fmt(
                    &mut out,
                    format_args!(
                        "                            web_search_tool_type: {},\n",
                        rust_str(required_str(model_obj, "web_search_tool_type")?)
                    ),
                )?;
                out.push_str("                            input_modalities: ");
                out.push_str(&rust_str_slice(required_str_array(
                    model_obj,
                    "input_modalities",
                )?));
                out.push_str(",\n");
                push_fmt(
                    &mut out,
                    format_args!(
                        "                            supports_image_detail_original: {},\n",
                        required_bool(model_obj, "supports_image_detail_original")?
                    ),
                )?;
                push_fmt(
                    &mut out,
                    format_args!(
                        "                            supports_search_tool: {},\n",
                        required_bool(model_obj, "supports_search_tool")?
                    ),
                )?;
                push_fmt(
                    &mut out,
                    format_args!(
                        "                            supports_parallel_tool_calls: {},\n",
                        required_bool(model_obj, "supports_parallel_tool_calls")?
                    ),
                )?;
                push_fmt(
                    &mut out,
                    format_args!(
                        "                            apply_patch_tool_type: {},\n",
                        rust_str(required_str(model_obj, "apply_patch_tool_type")?)
                    ),
                )?;
                out.push_str("                        },\n");
            }

            out.push_str("                    ],\n");
            out.push_str("                },\n");
        }

        out.push_str("            ],\n");
        out.push_str("        },\n");
    }

    out.push_str("    ],\n");
    out.push_str("};\n");
    Ok(out)
}

fn push_fmt(out: &mut String, args: fmt::Arguments<'_>) -> Result<(), String> {
    out.write_fmt(args)
        .map_err(|_err| "failed to render generated model catalog".to_string())
}

fn required_object<'a>(
    value: &'a serde_json::Map<String, Value>,
    field: &str,
) -> Result<&'a serde_json::Map<String, Value>, String> {
    value
        .get(field)
        .and_then(Value::as_object)
        .ok_or_else(|| format!("{field} must be an object"))
}

fn required_u64(value: &serde_json::Map<String, Value>, field: &str) -> Result<u64, String> {
    value
        .get(field)
        .and_then(Value::as_u64)
        .ok_or_else(|| format!("{field} must be an unsigned integer"))
}

fn required_bool(value: &serde_json::Map<String, Value>, field: &str) -> Result<bool, String> {
    value
        .get(field)
        .and_then(Value::as_bool)
        .ok_or_else(|| format!("{field} must be a boolean"))
}

fn required_str<'a>(
    value: &'a serde_json::Map<String, Value>,
    field: &str,
) -> Result<&'a str, String> {
    value
        .get(field)
        .and_then(Value::as_str)
        .ok_or_else(|| format!("{field} must be a string"))
}

fn required_array<'a>(
    value: &'a serde_json::Map<String, Value>,
    field: &str,
) -> Result<&'a [Value], String> {
    value
        .get(field)
        .and_then(Value::as_array)
        .map(Vec::as_slice)
        .ok_or_else(|| format!("{field} must be an array"))
}

fn required_str_array<'a>(
    value: &'a serde_json::Map<String, Value>,
    field: &str,
) -> Result<Vec<&'a str>, String> {
    required_array(value, field)?
        .iter()
        .map(|item| {
            item.as_str()
                .ok_or_else(|| format!("{field} entries must be strings"))
        })
        .collect()
}

fn rust_str(value: &str) -> String {
    format!("{value:?}")
}

fn rust_u64(value: u64) -> String {
    let digits = value.to_string();
    if digits.len() <= 3 {
        return digits;
    }

    let mut out = String::with_capacity(digits.len() + ((digits.len() - 1) / 3));
    let first_group_len = match digits.len() % 3 {
        0 => 3,
        len => len,
    };
    out.push_str(&digits[..first_group_len]);

    let mut index = first_group_len;
    while index < digits.len() {
        out.push('_');
        out.push_str(&digits[index..index + 3]);
        index += 3;
    }
    out
}

fn rust_str_slice(values: Vec<&str>) -> String {
    let mut out = String::from("&[");
    for value in values {
        out.push_str(&rust_str(value));
        out.push_str(", ");
    }
    out.push(']');
    out
}
